### ISSUE TITLE
Change Simulation Protobuf Structure to Contain More Info

### ISSUE THREAD

**Issue by RainierBarrett** [ur-whitelab/project-arc#1]
Re-work the protobufs for kinetics objects to allow for sending of not just mole fractions but also:
 - list of chemical species (e.g. "H2O," "CH4") -- **make sure these correspond to the mole fractions!**
 - Actual mole fractions (the current implementation has this)
 - _AND_ molar flow rates (current implementation _sends_ these but they're called mole _fractions_)

After this change, see open issues in the sim code and Unity and apply corresponding changes there. In short: make sure everything that uses the kinetics protobufs actually works after this change.

**Comment by t-sahin** [comment]
The changes were made and pushed.
